[request_definition]
r = sub, org, act, obj, ctx

[policy_definition]
p = org, sub, act, obj, ctx, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (p.sub == "anonymous" || (r.sub != "anonymous" && p.sub == "authenticated") || g(r.sub, p.sub, r.org) || g(r.sub, p.sub, p.org)) && (p.org == r.org || p.org == "platform") && (p.obj == "*" || keyMatch(r.obj, p.obj)) && (p.act == r.act || p.act == "manage") && (p.ctx == r.ctx || p.ctx == "any")
