[request_definition]
r = sub, org, act, obj, ctx

[policy_definition]
p = org, role, act, view, ctx, eft

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.role, r.org) || g(r.sub, p.role, p.org)) && (p.org == r.org || p.org == "platform") && (p.view == "*" || keyMatch(r.obj, p.view)) && (p.act == r.act || p.act == "manage") && (p.ctx == r.ctx || p.ctx == "any")
